# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99f5a99cf22c42072c03ee8db1978edb7b121fc0506eb91ef7d8381411b3d4a7008e328e4cfb1ef2e7708012e67787de9e05c5bb68c5c36ee4907c4b13f4a69d

test:
  secret_key_base: effa6e2c04e3f097146a9f8938304918a1993f8629c6711653e7d78d1a2c9755d740264d7f96d2a5206e0c6a82005ab3c21d0eef7f7e1d1a4727bebbd29c1038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
